package dev.comon.toss_watch.core.designsystem.theme

import androidx.compose.ui.graphics.Color

// Toss Watch 디자인 토큰 — DESIGN.md(라이트) / DESIGN_DARK.md(다크)의 전체 M3 시맨틱 팔레트 반영.

// ---- Light (DESIGN.md) ----
val SurfaceLight = Color(0xFFF8F9FF)
val SurfaceDimLight = Color(0xFFD4DAE7)
val SurfaceBrightLight = Color(0xFFF8F9FF)
val SurfaceContainerLowestLight = Color(0xFFFFFFFF)
val SurfaceContainerLowLight = Color(0xFFEFF3FF)
val SurfaceContainerLight = Color(0xFFE8EEFB)
val SurfaceContainerHighLight = Color(0xFFE3E8F5)
val SurfaceContainerHighestLight = Color(0xFFDDE3F0)
val OnSurfaceLight = Color(0xFF161C25)
val OnSurfaceVariantLight = Color(0xFF424656)
val InverseSurfaceLight = Color(0xFF2B313B)
val InverseOnSurfaceLight = Color(0xFFEBF1FE)
val OutlineLight = Color(0xFF737687)
val OutlineVariantLight = Color(0xFFC2C6D8)
val SurfaceTintLight = Color(0xFF0054D8)
val PrimaryLight = Color(0xFF004ECB)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFF0064FF)
val OnPrimaryContainerLight = Color(0xFFF5F5FF)
val InversePrimaryLight = Color(0xFFB3C5FF)
val SecondaryLight = Color(0xFF006D32)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFF55FD8C)
val OnSecondaryContainerLight = Color(0xFF007235)
val TertiaryLight = Color(0xFFB40009)
val OnTertiaryLight = Color(0xFFFFFFFF)
val TertiaryContainerLight = Color(0xFFDC1F1B)
val OnTertiaryContainerLight = Color(0xFFFFF3F1)
val ErrorLight = Color(0xFFBA1A1A)
val OnErrorLight = Color(0xFFFFFFFF)
val ErrorContainerLight = Color(0xFFFFDAD6)
val OnErrorContainerLight = Color(0xFF93000A)
val BackgroundLight = Color(0xFFF8F9FF)
val OnBackgroundLight = Color(0xFF161C25)
val SurfaceVariantLight = Color(0xFFDDE3F0)

// ---- Dark (DESIGN_DARK.md) ----
val SurfaceDark = Color(0xFF0D141D)
val SurfaceDimDark = Color(0xFF0D141D)
val SurfaceBrightDark = Color(0xFF333944)
val SurfaceContainerLowestDark = Color(0xFF080E17)
val SurfaceContainerLowDark = Color(0xFF161C25)
val SurfaceContainerDark = Color(0xFF1A2029)
val SurfaceContainerHighDark = Color(0xFF242A34)
val SurfaceContainerHighestDark = Color(0xFF2F353F)
val OnSurfaceDark = Color(0xFFDDE3F0)
val OnSurfaceVariantDark = Color(0xFFC2C6D8)
val InverseSurfaceDark = Color(0xFFDDE3F0)
val InverseOnSurfaceDark = Color(0xFF2B313B)
val OutlineDark = Color(0xFF8C90A2)
val OutlineVariantDark = Color(0xFF424656)
val SurfaceTintDark = Color(0xFFB3C5FF)
val PrimaryDark = Color(0xFFB3C5FF)
val OnPrimaryDark = Color(0xFF002A76)
val PrimaryContainerDark = Color(0xFF0064FF)
val OnPrimaryContainerDark = Color(0xFFF5F5FF)
val InversePrimaryDark = Color(0xFF0054D8)
val SecondaryDark = Color(0xFF42EE7F)
val OnSecondaryDark = Color(0xFF003917)
val SecondaryContainerDark = Color(0xFF01D166)
val OnSecondaryContainerDark = Color(0xFF005324)
val TertiaryDark = Color(0xFFFFB4AA)
val OnTertiaryDark = Color(0xFF690003)
val TertiaryContainerDark = Color(0xFFDC1F1B)
val OnTertiaryContainerDark = Color(0xFFFFF3F1)
val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)
val ErrorContainerDark = Color(0xFF93000A)
val OnErrorContainerDark = Color(0xFFFFDAD6)
val BackgroundDark = Color(0xFF0D141D)
val OnBackgroundDark = Color(0xFFDDE3F0)
val SurfaceVariantDark = Color(0xFF2F353F)

// ---- Fixed (라이트/다크 공통, M3 Fixed 컬러는 테마 불변) ----
val PrimaryFixed = Color(0xFFDBE1FF)
val PrimaryFixedDim = Color(0xFFB3C5FF)
val OnPrimaryFixed = Color(0xFF00174A)
val OnPrimaryFixedVariant = Color(0xFF003EA6)
val SecondaryFixed = Color(0xFF64FF92)
val SecondaryFixedDim = Color(0xFF30E375)
val OnSecondaryFixed = Color(0xFF00210B)
val OnSecondaryFixedVariant = Color(0xFF005224)
val TertiaryFixed = Color(0xFFFFDAD5)
val TertiaryFixedDim = Color(0xFFFFB4AA)
val OnTertiaryFixed = Color(0xFF410001)
val OnTertiaryFixedVariant = Color(0xFF930005)

// ---- 확장 시맨틱 컬러 (국내 시세 관례: 상승 빨강 / 하락 파랑) ----
// DESIGN.md 원문은 서구권 관례(Rise=Green/Fall=Red)를 제시하지만, 국내 증권 앱 사용자에게
// 익숙한 상승=빨강/하락=파랑 관례를 그대로 유지한다 (기존 Red40/Blue40 값과 동일).
// 등락 표시는 secondary/tertiary가 아닌 별도 고정 컬러로 노출해 라이트/다크 어디서나 동일한 의미를 갖는다.
val RiseRed = Color(0xFFD22030)
val FallBlue = Color(0xFF0064FF)
